//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int AId { get; set; }
        public Nullable<int> UId { get; set; }
        public string Name { get; set; }
        public string Building { get; set; }
        public string street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string phoneNo { get; set; }
        public int Pincode { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
