//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CartId { get; set; }
        public Nullable<double> OrderPrice { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public Nullable<int> Coins { get; set; }
        public string Coupon { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Coupon Coupon1 { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
